from django.conf import settings
from django.db import models
from django.utils import timezone
from django.utils.encoding import python_2_unicode_compatible


class Post(models.Model):
	author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete = models.CASCADE)
	job = models.CharField(max_length = 200)
	jobtitle = models.TextField()
	startdate = models.CharField(max_length = 200,null = True, blank = True)
	lastdate = models.CharField(max_length = 200,null = True, blank = True)
	feedate = models.CharField(max_length = 200,null = True, blank = True)
	examdate = models.CharField(max_length = 200,null = True, blank = True)
	generalfee = models.CharField(max_length = 200,null = True, blank = True)
	obcfee = models.CharField(max_length = 200,null = True, blank = True)
	exarmyfee = models.CharField(max_length = 200,null = True, blank = True)
	handycapfee = models.CharField(max_length = 200,null = True, blank = True)
	girlfee = models.CharField(max_length = 200,null = True, blank = True)
	post1 = models.CharField(max_length = 200,null = True, blank = True)
	post1vacncy = models.CharField(max_length = 200,null = True, blank = True)
	post1qulification = models.CharField(max_length = 200,null = True, blank = True)
	post1qulification2 = models.CharField(max_length = 200,null = True, blank = True)
	post1qulification3 = models.CharField(max_length = 200,null = True, blank = True)
	post1qulification4 = models.CharField(max_length = 200,null = True, blank = True)
	post1qulification5 = models.CharField(max_length = 200,null = True, blank = True)
	post1qulification6 = models.CharField(max_length = 200,null = True, blank = True)
	post2 = models.CharField(max_length = 200,null = True, blank = True)
	post2vacncy = models.CharField(max_length = 200,null = True, blank = True)
	post2qulification = models.CharField(max_length = 200,null = True, blank = True)
	post2qulification2 = models.CharField(max_length = 200,null = True, blank = True)
	post2qulification3 = models.CharField(max_length = 200,null = True, blank = True)
	post2qulification4 = models.CharField(max_length = 200,null = True, blank = True)
	post2qulification5 = models.CharField(max_length = 200,null = True, blank = True)
	post2qulification6 = models.CharField(max_length = 200,null = True, blank = True)
	post3 = models.CharField(max_length = 200,null = True, blank = True)
	post3vacncy = models.CharField(max_length = 200,null = True, blank = True)
	post3qulification = models.CharField(max_length = 200,null = True, blank = True)
	post3qulification2 = models.CharField(max_length = 200,null = True, blank = True)
	post3qulification3 = models.CharField(max_length = 200,null = True, blank = True)
	post3qulification4 = models.CharField(max_length = 200,null = True, blank = True)
	post3qulification5 = models.CharField(max_length = 200,null = True, blank = True)
	post3qulification6 = models.CharField(max_length = 200,null = True, blank = True)
	post4 = models.CharField(max_length = 200,null = True, blank = True)
	post4vacncy = models.CharField(max_length = 200,null = True, blank = True)
	post4qulification = models.CharField(max_length = 200,null = True, blank = True)
	post4qulification2 = models.CharField(max_length = 200,null = True, blank = True)
	post4qulification3 = models.CharField(max_length = 200,null = True, blank = True)
	post4qulification4 = models.CharField(max_length = 200,null = True, blank = True)
	post4qulification5 = models.CharField(max_length = 200,null = True, blank = True)
	post4qulification6 = models.CharField(max_length = 200,null = True, blank = True)
	post5 = models.CharField(max_length = 200,null = True, blank = True)
	post5vacncy = models.CharField(max_length = 200,null = True, blank = True)
	post5qulification = models.CharField(max_length = 200,null = True, blank = True)
	post5qulification2 = models.CharField(max_length = 200,null = True, blank = True)
	post5qulification3 = models.CharField(max_length = 200,null = True, blank = True)
	post5qulification4 = models.CharField(max_length = 200,null = True, blank = True)
	post5qulification5 = models.CharField(max_length = 200,null = True, blank = True)
	post5qulification6 = models.CharField(max_length = 200,null = True, blank = True)
	post6 = models.CharField(max_length = 200,null = True, blank = True)
	post6vacncy = models.CharField(max_length = 200,null = True, blank = True)
	post6qulification = models.CharField(max_length = 200,null = True, blank = True)
	post6qulification2 = models.CharField(max_length = 200,null = True, blank = True)
	post6qulification3 = models.CharField(max_length = 200,null = True, blank = True)
	post6qulification4 = models.CharField(max_length = 200,null = True, blank = True)
	post6qulification5 = models.CharField(max_length = 200,null = True, blank = True)
	post6qulification6 = models.CharField(max_length = 200,null = True, blank = True)
	post7 = models.CharField(max_length = 200,null = True, blank = True)
	post7vacncy = models.CharField(max_length = 200,null = True, blank = True)
	post7qulification = models.CharField(max_length = 200,null = True, blank = True)
	post7qulification2 = models.CharField(max_length = 200,null = True, blank = True)
	post7qulification3 = models.CharField(max_length = 200,null = True, blank = True)
	post7qulification4 = models.CharField(max_length = 200,null = True, blank = True)
	post7qulification5 = models.CharField(max_length = 200,null = True, blank = True)
	post7qulification6 = models.CharField(max_length = 200,null = True, blank = True)
	post7 = models.CharField(max_length = 200,null = True, blank = True)
	post8vacncy = models.CharField(max_length = 200,null = True, blank = True)
	post8qulification = models.CharField(max_length = 200,null = True, blank = True)
	post8qulification2 = models.CharField(max_length = 200,null = True, blank = True)
	post8qulification3 = models.CharField(max_length = 200,null = True, blank = True)
	post8qulification4 = models.CharField(max_length = 200,null = True, blank = True)
	post8qulification5 = models.CharField(max_length = 200,null = True, blank = True)
	post8qulification6 = models.CharField(max_length = 200,null = True, blank = True)
	post9 = models.CharField(max_length = 200,null = True, blank = True)
	post9vacncy = models.CharField(max_length = 200,null = True, blank = True)
	post9qulification = models.CharField(max_length = 200,null = True, blank = True)
	post9qulification2 = models.CharField(max_length = 200,null = True, blank = True)
	post9qulification3 = models.CharField(max_length = 200,null = True, blank = True)
	post9qulification4 = models.CharField(max_length = 200,null = True, blank = True)
	post9qulification5 = models.CharField(max_length = 200,null = True, blank = True)
	post9qulification6 = models.CharField(max_length = 200,null = True, blank = True)
	post10 = models.CharField(max_length = 200,null = True, blank = True)
	post10vacncy = models.CharField(max_length = 200,null = True, blank = True)
	post10qulification = models.CharField(max_length = 200,null = True, blank = True)
	post10qulification2 = models.CharField(max_length = 200,null = True, blank = True)
	post10qulification4 = models.CharField(max_length = 200,null = True, blank = True)
	post10qulification5 = models.CharField(max_length = 200,null = True, blank = True)
	post10qulification6 = models.CharField(max_length = 200,null = True, blank = True)
	post11 = models.CharField(max_length = 200,null = True, blank = True)
	post11vacncy = models.CharField(max_length = 200,null = True, blank = True)
	post11qulification = models.CharField(max_length = 200,null = True, blank = True)
	post11qulification2 = models.CharField(max_length = 200,null = True, blank = True)
	post11qulification3 = models.CharField(max_length = 200,null = True, blank = True)
	post11qulification4 = models.CharField(max_length = 200,null = True, blank = True)
	post11qulification5 = models.CharField(max_length = 200,null = True, blank = True)
	post11qulification6 = models.CharField(max_length = 200,null = True, blank = True)
	officialwebsite = models.CharField(max_length = 200,null = True, blank = True)
	applylink = models.CharField(max_length = 200,null = True, blank = True)
	loginlink = models.CharField(max_length = 200,null = True, blank = True)
	applylink2 = models.CharField(max_length = 200,null = True, blank = True)
	loginlink2 = models.CharField(max_length = 200,null = True, blank = True)
	examnotice = models.CharField(max_length = 200,null = True, blank = True)
	examnotice2 = models.CharField(max_length = 200,null = True, blank = True)
	admitcardlink = models.CharField(max_length = 200,null = True, blank = True)
	reserve = models.CharField(max_length = 200,null = True, blank = True)
	screnshot = models.FileField(upload_to = 'images/p/', null = True,blank = True)
	created_date = models.DateTimeField(default = timezone.now)
	published_date = models.DateTimeField(blank = True, null = True)

	def publish(self):
		self.published_date = timezone.now()
		self.save()

	def __str__(self):
		return self.job
  
  
class Admit(models.Model):
	author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete = models.CASCADE)
	admitdetails = models.CharField(max_length = 200)
	admitdetailstitle = models.TextField()
	startdate = models.CharField(max_length = 200,null = True, blank = True)
	lastdate = models.CharField(max_length = 200,null = True, blank = True)
	feedate = models.CharField(max_length = 200,null = True, blank = True)
	examdate = models.CharField(max_length = 200,null = True, blank = True)
	generalfee = models.CharField(max_length = 200,null = True, blank = True)
	obcfee = models.CharField(max_length = 200,null = True, blank = True)
	exarmyfee = models.CharField(max_length = 200,null = True, blank = True)
	handycapfee = models.CharField(max_length = 200,null = True, blank = True)
	girlfee = models.CharField(max_length = 200,null = True, blank = True)
	post1 = models.CharField(max_length = 200,null = True, blank = True)
	post1vacncy = models.CharField(max_length = 200,null = True, blank = True)
	post1qulification = models.CharField(max_length = 200,null = True, blank = True)
	post1qulification2 = models.CharField(max_length = 200,null = True, blank = True)
	post1qulification3 = models.CharField(max_length = 200,null = True, blank = True)
	post1qulification4 = models.CharField(max_length = 200,null = True, blank = True)
	post1qulification5 = models.CharField(max_length = 200,null = True, blank = True)
	post1qulification6 = models.CharField(max_length = 200,null = True, blank = True)
	admitcardlink = models.CharField(max_length = 200,null = True, blank = True)	
	officialwebsite = models.CharField(max_length = 200,null = True, blank = True)
	applylink = models.CharField(max_length = 200,null = True, blank = True)
	loginlink = models.CharField(max_length = 200,null = True, blank = True)
	applylink2 = models.CharField(max_length = 200,null = True, blank = True)
	loginlink2 = models.CharField(max_length = 200,null = True, blank = True)
	examnotice = models.CharField(max_length = 200,null = True, blank = True)
	examnotice2 = models.CharField(max_length = 200,null = True, blank = True)
	admitcardlink = models.CharField(max_length = 200,null = True, blank = True)
	reserve = models.CharField(max_length = 200,null = True, blank = True)
	screnshot = models.FileField(upload_to = 'images/p/', null = True,blank = True)
	created_date = models.DateTimeField(default = timezone.now)
	published_date = models.DateTimeField(blank = True, null = True)

	def publish(self):
		self.published_date = timezone.now()
		self.save()

	def __str__(self):
		return self.admitdetails
  
class Result(models.Model):
	author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete = models.CASCADE)
	resultdetails = models.CharField(max_length = 200)
	resultdetailstitle = models.TextField()
	startdate = models.CharField(max_length = 200,null = True, blank = True)
	lastdate = models.CharField(max_length = 200,null = True, blank = True)
	feedate = models.CharField(max_length = 200,null = True, blank = True)
	examdate = models.CharField(max_length = 200,null = True, blank = True)
	generalfee = models.CharField(max_length = 200,null = True, blank = True)
	obcfee = models.CharField(max_length = 200,null = True, blank = True)
	exarmyfee = models.CharField(max_length = 200,null = True, blank = True)
	handycapfee = models.CharField(max_length = 200,null = True, blank = True)
	girlfee = models.CharField(max_length = 200,null = True, blank = True)
	post1 = models.CharField(max_length = 200,null = True, blank = True)
	post1vacncy = models.CharField(max_length = 200,null = True, blank = True)
	post1qulification = models.CharField(max_length = 200,null = True, blank = True)
	post1qulification2 = models.CharField(max_length = 200,null = True, blank = True)
	post1qulification3 = models.CharField(max_length = 200,null = True, blank = True)
	post1qulification4 = models.CharField(max_length = 200,null = True, blank = True)
	post1qulification5 = models.CharField(max_length = 200,null = True, blank = True)
	post1qulification6 = models.CharField(max_length = 200,null = True, blank = True)
	answerkeylink = models.CharField(max_length = 200,null = True, blank = True)	
	officialwebsite = models.CharField(max_length = 200,null = True, blank = True)
	applylink = models.CharField(max_length = 200,null = True, blank = True)
	loginlink = models.CharField(max_length = 200,null = True, blank = True)
	applylink2 = models.CharField(max_length = 200,null = True, blank = True)
	loginlink2 = models.CharField(max_length = 200,null = True, blank = True)
	examnotice = models.CharField(max_length = 200,null = True, blank = True)
	examnotice2 = models.CharField(max_length = 200,null = True, blank = True)
	admitcardlink = models.CharField(max_length = 200,null = True, blank = True)
	reserve = models.CharField(max_length = 200,null = True, blank = True)
	screnshot = models.FileField(upload_to = 'images/p/', null = True,blank = True)
	created_date = models.DateTimeField(default = timezone.now)
	published_date = models.DateTimeField(blank = True, null = True)

	def publish(self):
		self.published_date = timezone.now()
		self.save()

	def __str__(self):
		return self.resultdetails
  
class Answer(models.Model):
	author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete = models.CASCADE)
	answeredetails = models.CharField(max_length = 200)
	answeredetailstitle = models.TextField()
	startdate = models.CharField(max_length = 200,null = True, blank = True)
	lastdate = models.CharField(max_length = 200,null = True, blank = True)
	feedate = models.CharField(max_length = 200,null = True, blank = True)
	examdate = models.CharField(max_length = 200,null = True, blank = True)
	generalfee = models.CharField(max_length = 200,null = True, blank = True)
	obcfee = models.CharField(max_length = 200,null = True, blank = True)
	exarmyfee = models.CharField(max_length = 200,null = True, blank = True)
	handycapfee = models.CharField(max_length = 200,null = True, blank = True)
	girlfee = models.CharField(max_length = 200,null = True, blank = True)
	post1 = models.CharField(max_length = 200,null = True, blank = True)
	post1vacncy = models.CharField(max_length = 200,null = True, blank = True)
	post1qulification = models.CharField(max_length = 200,null = True, blank = True)
	post1qulification2 = models.CharField(max_length = 200,null = True, blank = True)
	post1qulification3 = models.CharField(max_length = 200,null = True, blank = True)
	post1qulification4 = models.CharField(max_length = 200,null = True, blank = True)
	post1qulification5 = models.CharField(max_length = 200,null = True, blank = True)
	post1qulification6 = models.CharField(max_length = 200,null = True, blank = True)
	answerkeylink = models.CharField(max_length = 200,null = True, blank = True)	
	officialwebsite = models.CharField(max_length = 200,null = True, blank = True)
	applylink = models.CharField(max_length = 200,null = True, blank = True)
	loginlink = models.CharField(max_length = 200,null = True, blank = True)
	applylink2 = models.CharField(max_length = 200,null = True, blank = True)
	loginlink2 = models.CharField(max_length = 200,null = True, blank = True)
	examnotice = models.CharField(max_length = 200,null = True, blank = True)
	examnotice2 = models.CharField(max_length = 200,null = True, blank = True)
	admitcardlink = models.CharField(max_length = 200,null = True, blank = True)
	reserve = models.CharField(max_length = 200,null = True, blank = True)
	screnshot = models.FileField(upload_to = 'images/p/', null = True,blank = True)
	created_date = models.DateTimeField(default = timezone.now)
	published_date = models.DateTimeField(blank = True, null = True)

	def publish(self):
		self.published_date = timezone.now()
		self.save()

	def __str__(self):
		return self.answeredetails
  
class Admission(models.Model):
	author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete = models.CASCADE)
	importantlinkdetails = models.CharField(max_length = 200)
	admissiontitle = models.TextField()
	startdate = models.CharField(max_length = 200,null = True, blank = True)
	lastdate = models.CharField(max_length = 200,null = True, blank = True)
	feedate = models.CharField(max_length = 200,null = True, blank = True)
	examdate = models.CharField(max_length = 200,null = True, blank = True)
	generalfee = models.CharField(max_length = 200,null = True, blank = True)
	obcfee = models.CharField(max_length = 200,null = True, blank = True)
	exarmyfee = models.CharField(max_length = 200,null = True, blank = True)
	handycapfee = models.CharField(max_length = 200,null = True, blank = True)
	girlfee = models.CharField(max_length = 200,null = True, blank = True)
	post1 = models.CharField(max_length = 200,null = True, blank = True)
	post1vacncy = models.CharField(max_length = 200,null = True, blank = True)
	post1qulification = models.CharField(max_length = 200,null = True, blank = True)
	post1qulification2 = models.CharField(max_length = 200,null = True, blank = True)
	post1qulification3 = models.CharField(max_length = 200,null = True, blank = True)
	post1qulification4 = models.CharField(max_length = 200,null = True, blank = True)
	post1qulification5 = models.CharField(max_length = 200,null = True, blank = True)
	post1qulification6 = models.CharField(max_length = 200,null = True, blank = True)
	importanlink = models.CharField(max_length = 200,null = True, blank = True)	
	officialwebsite = models.CharField(max_length = 200,null = True, blank = True)
	applylink = models.CharField(max_length = 200,null = True, blank = True)
	loginlink = models.CharField(max_length = 200,null = True, blank = True)
	applylink2 = models.CharField(max_length = 200,null = True, blank = True)
	loginlink2 = models.CharField(max_length = 200,null = True, blank = True)
	examnotice = models.CharField(max_length = 200,null = True, blank = True)
	examnotice2 = models.CharField(max_length = 200,null = True, blank = True)
	admitcardlink = models.CharField(max_length = 200,null = True, blank = True)
	reserve = models.CharField(max_length = 200,null = True, blank = True)
	screnshot = models.FileField(upload_to = 'images/p/', null = True,blank = True)
	created_date = models.DateTimeField(default = timezone.now)
	published_date = models.DateTimeField(blank = True, null = True)

	def publish(self):
		self.published_date = timezone.now()
		self.save()

	def __str__(self):
		return self.importantlink  
  
  
class Important(models.Model):
	author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete = models.CASCADE)
	importantlinktitle = models.CharField(max_length = 200)
	importantlinkdetails = models.TextField()
	startdate = models.CharField(max_length = 200,null = True, blank = True)
	lastdate = models.CharField(max_length = 200,null = True, blank = True)
	feedate = models.CharField(max_length = 200,null = True, blank = True)
	examdate = models.CharField(max_length = 200,null = True, blank = True)
	generalfee = models.CharField(max_length = 200,null = True, blank = True)
	obcfee = models.CharField(max_length = 200,null = True, blank = True)
	exarmyfee = models.CharField(max_length = 200,null = True, blank = True)
	handycapfee = models.CharField(max_length = 200,null = True, blank = True)
	girlfee = models.CharField(max_length = 200,null = True, blank = True)
	post1 = models.CharField(max_length = 200,null = True, blank = True)
	post1vacncy = models.CharField(max_length = 200,null = True, blank = True)
	post1qulification = models.CharField(max_length = 200,null = True, blank = True)
	post1qulification2 = models.CharField(max_length = 200,null = True, blank = True)
	post1qulification3 = models.CharField(max_length = 200,null = True, blank = True)
	post1qulification4 = models.CharField(max_length = 200,null = True, blank = True)
	post1qulification5 = models.CharField(max_length = 200,null = True, blank = True)
	post1qulification6 = models.CharField(max_length = 200,null = True, blank = True)
	importanlink = models.CharField(max_length = 200,null = True, blank = True)	
	officialwebsite = models.CharField(max_length = 200,null = True, blank = True)
	applylink = models.CharField(max_length = 200,null = True, blank = True)
	loginlink = models.CharField(max_length = 200,null = True, blank = True)
	applylink2 = models.CharField(max_length = 200,null = True, blank = True)
	loginlink2 = models.CharField(max_length = 200,null = True, blank = True)
	examnotice = models.CharField(max_length = 200,null = True, blank = True)
	examnotice2 = models.CharField(max_length = 200,null = True, blank = True)
	admitcardlink = models.CharField(max_length = 200,null = True, blank = True)
	reserve = models.CharField(max_length = 200,null = True, blank = True)
	screnshot = models.FileField(upload_to = 'images/p/', null = True,blank = True)
	created_date = models.DateTimeField(default = timezone.now)
	published_date = models.DateTimeField(blank = True, null = True)

	def publish(self):
		self.published_date = timezone.now()
		self.save()

	def __str__(self):
		return self.importantlinktitle
  
